### ISSUE TITLE
Console error message with 10.6.8

### ISSUE THREAD

**Issue by MSERobert** [afragen/git-updater#975]
I'm seeing an odd console error with the latest version installed. I downgraded to 10.6.7 and it went away. As shown in the image I'm seeing a 404 message for a file in my child theme that doesn't exist.

![image](https://user-images.githubusercontent.com/63687283/146682138-dae82ca7-15ca-4935-bdb9-6ba04fff973b.png)

**Comment by afragen** [comment]
I don't see any way the changes from 10.6.7 to 10.6.8 could be causing this issue in another plugin. 

What are you doing when you see this error?

**Comment by afragen** [comment]
Can you share a list of active plugins and your active theme?

**Comment by MSERobert** [comment]
Plugins:
advanced-custom-fields-pro
event-tickets
event-tickets-plus
events-calendar-pro
git-updater
gravityforms
gravityformsmailchimp
iva-business-hours-pro
members
mycred
query-monitor
sf-move-login
surbma-divi-gravity-forms
the-events-calendar
user-switching
woocommerce
woocommerce-bookings
woocommerce-gateway-stripe
woocommerce-product-addons
woocommerce-smart-coupons
woocommerce-terms-conditions-popup
woocommerce-tipping
wp-crontrol
wp-mail-smtp-pro

Theme:
Divi

**Comment by MSERobert** [comment]
I did come across something else. I updated git-updater on a couple of other sites but it only seems to be a problem on my local VM. I also came across this error on my VM:

![image](https://user-images.githubusercontent.com/63687283/146688876-05a8a362-ea7d-4aaa-8bab-bcc0003684ff.png)

**Comment by afragen** [comment]
I see the problem. You have a self-signed certificate and my check is returning a WP_Error and so it thinks the file is in the theme's vendor folder.

I think I've solved the issue. https://github.com/afragen/wp-dismiss-notice/commit/3b9d3b775fcffdeabab1fcba49514b8992bdded8

Let me know if 10.6.9 solves the issue. FWIW you will still get the cURL error but you shouldn't get the 404. The cURL error is because you have a self-signed certificate for your VM. I don't really know how to solve that.
